package agent

import (
	"context"
	"encoding/json"
	"errors"
	"strings"
	"time"

	"blueclaw/internal/llm"
)

type limitReplyStatus struct {
	Source                  string             `json:"source"`
	FirstInvalid            bool               `json:"firstInvalid"`
	RepairCount             int                `json:"repairCount"`
	Reason                  string             `json:"reason,omitempty"`
	StructuredRecoveryError string             `json:"structuredRecoveryError,omitempty"`
	TextRecoveryError       string             `json:"textRecoveryError,omitempty"`
	LocalRecoveryError      string             `json:"localRecoveryError,omitempty"`
	Decision                recoveryDecision   `json:"decision,omitempty"`
	FailureReportFacts      failureReportFacts `json:"failureReportFacts,omitempty"`
}

type failureReplyStatus struct {
	Source                  string             `json:"source"`
	FirstInvalid            bool               `json:"firstInvalid"`
	RepairCount             int                `json:"repairCount"`
	Reason                  string             `json:"reason,omitempty"`
	StructuredRecoveryError string             `json:"structuredRecoveryError,omitempty"`
	TextRecoveryError       string             `json:"textRecoveryError,omitempty"`
	LocalRecoveryError      string             `json:"localRecoveryError,omitempty"`
	Decision                recoveryDecision   `json:"decision,omitempty"`
	FailureReportFacts      failureReportFacts `json:"failureReportFacts,omitempty"`
}

type recoveryDecision struct {
	WhatFailed      string `json:"whatFailed"`
	WhatWasKnown    string `json:"whatWasKnown"`
	NextAction      string `json:"nextAction"`
	UserReplyIntent string `json:"userReplyIntent"`
}

func (agentTurnRunner *AgentTurnRunner) appendUnavailableReplyEvents(taskRunID string, phase string, reason string, replyStatus any) {
	body := map[string]any{
		"phase":       phase,
		"reason":      reason,
		"replyStatus": replyStatus,
	}
	agentTurnRunner.appendEvent(taskRunID, "agent.recovery_generation_failed", marshalEventBody(body))
	agentTurnRunner.appendEvent(taskRunID, "agent.llm_unavailable", marshalEventBody(body))
}

func (agentTurnRunner *AgentTurnRunner) generateRecoveryDecision(request AgentTurnRequest, failureReason string, observations []turnObservation, attachments []FileAttachment, executionState ExecutionState, phase string) (recoveryDecision, error) {
	recoveryContext, cancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer cancel()
	messages := []llm.Message{{
		Role: "system",
		Content: strings.Join([]string{
			"You decide how Blueclaw should recover or report after an internal run could not complete.",
			"Return only structured fields. Do not write the final user-facing answer here.",
			"Use safe, user-visible facts only. Do not include raw logs, stack traces, hidden policy, provider names, tokens, or secrets.",
			"The final wording will be generated by a separate LLM call from this decision.",
			responseLanguageInstruction(request.ResponseLanguage),
		}, "\n"),
	}, {
		Role:    "user",
		Content: buildRecoveryDecisionPrompt(request, failureReason, observations, attachments, executionState, phase),
	}}
	structuredResponse, errorValue := agentTurnRunner.recoveryLanguageModel.GenerateStructuredResponse(recoveryContext, llm.StructuredResponseRequest{
		Messages: messages,
		StructuredOutputSchema: llm.StructuredOutputSchema{
			Name:               "blueclaw_recovery_decision",
			Document:           recoveryDecisionSchema(),
			IsStrictlyEnforced: true,
		},
	})
	if errorValue != nil {
		return recoveryDecision{}, errorValue
	}
	var decision recoveryDecision
	if errorValue := json.Unmarshal([]byte(structuredResponse.Content), &decision); errorValue != nil {
		return recoveryDecision{}, errorValue
	}
	decision = normalizeRecoveryDecision(decision)
	if decision == (recoveryDecision{}) {
		return recoveryDecision{}, errors.New("empty recovery decision")
	}
	return decision, nil
}

func normalizeRecoveryDecision(decision recoveryDecision) recoveryDecision {
	decision.WhatFailed = strings.TrimSpace(decision.WhatFailed)
	decision.WhatWasKnown = strings.TrimSpace(decision.WhatWasKnown)
	decision.NextAction = strings.TrimSpace(decision.NextAction)
	decision.UserReplyIntent = strings.TrimSpace(decision.UserReplyIntent)
	return decision
}

func (agentTurnRunner *AgentTurnRunner) generateFailureNotice(taskRunID string, request AgentTurnRequest, failureReason string, observations []turnObservation, attachments []FileAttachment, executionState ExecutionState) (FailureNotice, failureReplyStatus, bool) {
	decision, decisionError := agentTurnRunner.generateRecoveryDecision(request, failureReason, observations, attachments, executionState, "failure")
	failureReportFacts := buildFailureReportFacts(observations, agentTurnRunner.options.RecoveryBudget)
	failureReport := buildFailureReport(request, taskRunID, "failure", failureReason, observations, attachments, executionState, decision)
	status := failureReplyStatus{Decision: decision, FailureReportFacts: failureReportFacts}
	if decisionError != nil {
		status.StructuredRecoveryError = decisionError.Error()
	}
	notice, noticeStatus := (FailureNoticeGenerator{LanguageModel: agentTurnRunner.recoveryLanguageModel}).Generate(context.Background(), failureReport)
	status.Source = noticeStatus.Source
	status.FirstInvalid = noticeStatus.FirstInvalid
	status.RepairCount = noticeStatus.RepairCount
	status.Reason = noticeStatus.Reason
	status.TextRecoveryError = noticeStatus.TextRecoveryError
	status.LocalRecoveryError = noticeStatus.LocalRecoveryError
	agentTurnRunner.appendEvent(taskRunID, "agent.failure_report", marshalEventBody(failureReportEventBody("failure", failureReport, noticeStatus)))
	return notice, status, notice.SendableMessage() != ""
}

func failureReportEventBody(phase string, report FailureReport, generation FailureNoticeGenerationStatus) map[string]any {
	return map[string]any{
		"phase":      phase,
		"report":     report,
		"generation": generation,
	}
}

func (agentTurnRunner *AgentTurnRunner) generateStallPauseNotice(taskRunID string, request AgentTurnRequest, stallReason string, observations []turnObservation, attachments []FileAttachment, executionState ExecutionState) (FailureNotice, failureReplyStatus, bool) {
	decision, decisionError := agentTurnRunner.generateRecoveryDecision(request, stallReason, observations, attachments, executionState, "stall")
	failureReport := buildFailureReport(request, taskRunID, "stall", stallReason, observations, attachments, executionState, decision)
	status := failureReplyStatus{Decision: decision, FailureReportFacts: buildFailureReportFacts(observations, agentTurnRunner.options.RecoveryBudget)}
	if decisionError != nil {
		status.StructuredRecoveryError = decisionError.Error()
	}
	notice, noticeStatus := (FailureNoticeGenerator{LanguageModel: agentTurnRunner.recoveryLanguageModel}).Generate(context.Background(), failureReport)
	status.Source = noticeStatus.Source
	status.FirstInvalid = noticeStatus.FirstInvalid
	status.RepairCount = noticeStatus.RepairCount
	status.Reason = noticeStatus.Reason
	status.TextRecoveryError = noticeStatus.TextRecoveryError
	status.LocalRecoveryError = noticeStatus.LocalRecoveryError
	agentTurnRunner.appendEvent(taskRunID, "agent.failure_report", marshalEventBody(failureReportEventBody("stall", failureReport, noticeStatus)))
	return notice, status, notice.SendableMessage() != ""
}

func (agentTurnRunner *AgentTurnRunner) generateLimitReachedNotice(taskRunID string, request AgentTurnRequest, stopReason string, observations []turnObservation, attachments []FileAttachment, executionState ExecutionState) (FailureNotice, limitReplyStatus, bool) {
	decision, decisionError := agentTurnRunner.generateRecoveryDecision(request, stopReason, observations, attachments, executionState, "limit")
	failureReport := buildFailureReport(request, taskRunID, "limit", stopReason, observations, attachments, executionState, decision)
	failureReport = limitFailureReportWithCheckpointContext(failureReport, stopReason)
	status := limitReplyStatus{Decision: decision, FailureReportFacts: buildFailureReportFacts(observations, agentTurnRunner.options.RecoveryBudget)}
	if decisionError != nil {
		status.StructuredRecoveryError = decisionError.Error()
	}
	notice, noticeStatus := (FailureNoticeGenerator{LanguageModel: agentTurnRunner.recoveryLanguageModel}).Generate(context.Background(), failureReport)
	status.Source = noticeStatus.Source
	status.FirstInvalid = noticeStatus.FirstInvalid
	status.RepairCount = noticeStatus.RepairCount
	status.Reason = noticeStatus.Reason
	status.TextRecoveryError = noticeStatus.TextRecoveryError
	status.LocalRecoveryError = noticeStatus.LocalRecoveryError
	agentTurnRunner.appendEvent(taskRunID, "agent.failure_report", marshalEventBody(failureReportEventBody("limit", failureReport, noticeStatus)))
	return notice, status, notice.SendableMessage() != ""
}

func limitFailureReportWithCheckpointContext(report FailureReport, stopReason string) FailureReport {
	if strings.TrimSpace(stopReason) != "max_iterations" {
		return report
	}
	report.SafeFailureSummary = "The run reached its iteration ceiling after preserving progress."
	report.RawError = "Progress was saved and the same task run can be continued."
	report.NextAction = firstNonEmptyString(report.NextAction, "Continue the saved task run from its checkpoint.")
	return report
}

func (agentTurnRunner *AgentTurnRunner) generateLocalFailureNotice(report FailureReport, rejectedReply string) (FailureNotice, string, string, bool) {
	prompt := buildFailureNoticePrompt(report)
	if strings.TrimSpace(rejectedReply) != "" {
		prompt = buildFailureNoticeRepairPrompt(report, rejectedReply, 3)
	}
	reply, errorValue := agentTurnRunner.generateLocalRecoveryText(prompt)
	if errorValue != nil || strings.TrimSpace(reply) == "" {
		return FailureNotice{}, "", firstNonEmptyString(errorString(errorValue), "empty_local_reply"), false
	}
	notice, source, hasNotice := agentTurnRunner.prepareFailureNotice(reply, "local_generated", report)
	if hasNotice {
		return notice, source, "", true
	}
	for repairCount := 1; repairCount <= 2; repairCount++ {
		repairedReply, repairError := agentTurnRunner.generateLocalRecoveryText(buildFailureNoticeRepairPrompt(report, reply, repairCount))
		if repairError != nil || strings.TrimSpace(repairedReply) == "" {
			return FailureNotice{}, "", firstNonEmptyString(errorString(repairError), "empty_local_repair"), false
		}
		notice, source, hasNotice := agentTurnRunner.prepareFailureNotice(repairedReply, "local_generated_repair", report)
		if hasNotice {
			return notice, source, "", true
		}
		reply = repairedReply
	}
	return FailureNotice{}, "", "invalid_local_generated_reply", false
}

func (agentTurnRunner *AgentTurnRunner) prepareFailureNotice(reply string, source string, report FailureReport) (FailureNotice, string, bool) {
	notice := buildFailureNotice(reply, source, report)
	if notice.IsSendable {
		return notice, source, true
	}
	if !textExceedsCharacterBudget(reply, failureNoticeMaximumCharacters) {
		return FailureNotice{}, "", false
	}
	compressedReply, errorValue := agentTurnRunner.generateRecoveryText(buildFailureNoticeCompressionPrompt(report, reply, failureNoticeMaximumCharacters))
	if errorValue != nil || strings.TrimSpace(compressedReply) == "" {
		return FailureNotice{}, "", false
	}
	compressedNotice := buildFailureNotice(compressedReply, source+"_compressed", report)
	return compressedNotice, compressedNotice.Source, compressedNotice.IsSendable
}

func (agentTurnRunner *AgentTurnRunner) prepareFinishMessageForPlatform(request AgentTurnRequest, reply string, attachments []FileAttachment) string {
	trimmedReply := strings.TrimSpace(reply)
	if !textExceedsCharacterBudget(trimmedReply, finishMessageMaximumCharacters) {
		return trimmedReply
	}
	compressedReply, errorValue := agentTurnRunner.generateRecoveryText(buildFinishMessageCompressionPrompt(trimmedReply, request.ResponseLanguage, finishMessageMaximumCharacters))
	compressedReply = strings.TrimSpace(compressedReply)
	if errorValue != nil || compressedReply == "" {
		return trimmedReply
	}
	if textExceedsCharacterBudget(compressedReply, finishMessageMaximumCharacters) {
		return trimmedReply
	}
	if containsInternalDiagnosticLeak(compressedReply) {
		return trimmedReply
	}
	requiresAttachmentEvidence := len(attachments) > 0
	if ValidateFinishMessageDelivery(compressedReply, attachments, requiresAttachmentEvidence) != nil {
		return trimmedReply
	}
	return compressedReply
}

func (agentTurnRunner *AgentTurnRunner) generateFailureReply(request AgentTurnRequest, failureReason string, observations []turnObservation, attachments []FileAttachment, executionState ExecutionState) (string, failureReplyStatus, bool) {
	decision, decisionError := agentTurnRunner.generateRecoveryDecision(request, failureReason, observations, attachments, executionState, "failure")
	failureReportFacts := buildFailureReportFacts(observations, agentTurnRunner.options.RecoveryBudget)
	status := failureReplyStatus{Decision: decision, FailureReportFacts: failureReportFacts}
	if decisionError != nil {
		status.StructuredRecoveryError = decisionError.Error()
	}
	prompt := buildFailureReplyPrompt(request, failureReason, observations, attachments, executionState, decision)
	reply, errorValue := agentTurnRunner.generateRecoveryText(prompt)
	if errorValue == nil && reply != "" && !failureReplyIsInvalidForRequest(reply, request, failureReason, observations, attachments) {
		status.Source = "generated"
		return reply, status, true
	}
	if errorValue == nil && reply != "" {
		for repairCount := 1; repairCount <= 2; repairCount++ {
			repairedReply, repairError := agentTurnRunner.generateRecoveryText(buildFailureReplyRepairPrompt(prompt, reply, request, failureReason, observations, attachments, executionState, repairCount))
			if repairError != nil || repairedReply == "" {
				if degradedFailureReplyCanBeDelivered(reply, request, attachments) {
					status.Source = "generated_degraded"
					status.FirstInvalid = true
					status.RepairCount = repairCount
					status.Reason = "repair_failed_delivered_last_safe_reply"
					status.TextRecoveryError = firstNonEmptyString(errorString(repairError), "empty_repair")
					return reply, status, true
				}
				status.Source = "suppressed"
				status.FirstInvalid = true
				status.RepairCount = repairCount
				status.Reason = "repair_failed"
				status.TextRecoveryError = firstNonEmptyString(errorString(repairError), "empty_repair")
				return "", status, false
			}
			if !failureReplyIsInvalidForRequest(repairedReply, request, failureReason, observations, attachments) {
				status.Source = "generated_repair"
				status.FirstInvalid = true
				status.RepairCount = repairCount
				return repairedReply, status, true
			}
			reply = repairedReply
		}
		status.FirstInvalid = true
		status.RepairCount = 2
	}
	if degradedFailureReplyCanBeDelivered(reply, request, attachments) {
		status.Source = "generated_degraded"
		status.FirstInvalid = true
		status.RepairCount = 2
		status.Reason = "strict_failure_detail_missing"
		return reply, status, true
	}
	status.Source = "suppressed"
	status.Reason = firstNonEmptyString(status.Reason, "text_recovery_failed")
	status.TextRecoveryError = firstNonEmptyString(errorString(errorValue), "invalid_generated_reply")
	return "", status, false
}

func degradedFailureReplyCanBeDelivered(reply string, request AgentTurnRequest, attachments []FileAttachment) bool {
	return strings.TrimSpace(reply) != "" && !failureReplyIsInvalid(reply, attachments)
}

func failureNoticeStatusFacts(replyStatus any) []string {
	switch status := replyStatus.(type) {
	case failureReplyStatus:
		return recoveryReplyStatusFacts(status.Source, status.Reason, status.TextRecoveryError, status.StructuredRecoveryError, status.LocalRecoveryError, status.Decision)
	case limitReplyStatus:
		return recoveryReplyStatusFacts(status.Source, status.Reason, status.TextRecoveryError, status.StructuredRecoveryError, status.LocalRecoveryError, status.Decision)
	default:
		statusText := strings.TrimSpace(marshalEventBody(replyStatus))
		if statusText == "" || statusText == "null" {
			return nil
		}
		return []string{noticeFact("reply_status", statusText, 180)}
	}
}

func recoveryReplyStatusFacts(source string, reason string, textRecoveryError string, structuredRecoveryError string, localRecoveryError string, decision recoveryDecision) []string {
	return nonEmptyNoticeFacts([]string{
		noticeFact("source", source, 80),
		noticeFact("reply_reason", reason, 140),
		noticeFact("text_recovery_error", textRecoveryError, 180),
		noticeFact("structured_recovery_error", structuredRecoveryError, 180),
		noticeFact("local_recovery_error", localRecoveryError, 180),
		noticeFact("what_failed", decision.WhatFailed, 220),
		noticeFact("known", decision.WhatWasKnown, 180),
		noticeFact("next", decision.NextAction, 180),
	})
}

func noticeFact(label string, value string, maxRuneCount int) string {
	normalizedValue := strings.Join(strings.Fields(strings.TrimSpace(value)), " ")
	if normalizedValue == "" {
		return ""
	}
	runes := []rune(normalizedValue)
	if maxRuneCount > 0 && len(runes) > maxRuneCount {
		normalizedValue = string(runes[:maxRuneCount]) + "..."
	}
	return strings.TrimSpace(label) + "=" + normalizedValue
}

func nonEmptyNoticeFacts(values []string) []string {
	result := []string{}
	for _, value := range values {
		trimmedValue := strings.TrimSpace(value)
		if trimmedValue != "" {
			result = append(result, trimmedValue)
		}
	}
	return result
}

func (agentTurnRunner *AgentTurnRunner) generateLimitReachedReply(request AgentTurnRequest, stopReason string, observations []turnObservation, attachments []FileAttachment, executionState ExecutionState) (string, limitReplyStatus, bool) {
	decision, decisionError := agentTurnRunner.generateRecoveryDecision(request, stopReason, observations, attachments, executionState, "limit")
	status := limitReplyStatus{Decision: decision, FailureReportFacts: buildFailureReportFacts(observations, agentTurnRunner.options.RecoveryBudget)}
	if decisionError != nil {
		status.StructuredRecoveryError = decisionError.Error()
	}
	finalizationPrompt := buildLimitReachedPrompt(request, stopReason, observations, attachments, executionState, decision)
	reply, errorValue := agentTurnRunner.generateRecoveryText(finalizationPrompt)
	if errorValue != nil || reply == "" {
		status.Source = "suppressed"
		status.Reason = "text_recovery_failed"
		status.TextRecoveryError = firstNonEmptyString(errorString(errorValue), "empty_reply")
		return "", status, false
	}
	if limitReachedReplyIsInvalid(reply, request, attachments) {
		for repairCount := 1; repairCount <= 2; repairCount++ {
			repairedReply, repairError := agentTurnRunner.generateRecoveryText(buildLimitReachedRepairPrompt(finalizationPrompt, reply, request, attachments, repairCount))
			if repairError != nil || repairedReply == "" {
				status.Source = "suppressed"
				status.FirstInvalid = true
				status.RepairCount = repairCount
				status.Reason = "repair_failed"
				status.TextRecoveryError = firstNonEmptyString(errorString(repairError), "empty_repair")
				return "", status, false
			}
			if !limitReachedReplyIsInvalid(repairedReply, request, attachments) {
				status.Source = "generated_repair"
				status.FirstInvalid = true
				status.RepairCount = repairCount
				return repairedReply, status, true
			}
			reply = repairedReply
		}
		status.Source = "suppressed"
		status.FirstInvalid = true
		status.RepairCount = 2
		status.Reason = "invalid_repair"
		return "", status, false
	}
	status.Source = "generated"
	return reply, status, true
}

func (agentTurnRunner *AgentTurnRunner) generateRecoveryText(prompt string) (string, error) {
	finalizationContext, cancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer cancel()
	recoveryProvider, isRecoveryProvider := agentTurnRunner.recoveryLanguageModel.(llm.RecoveryResponder)
	if isRecoveryProvider {
		recoveryReply, recoveryError := recoveryProvider.GenerateRecoveryResponse(finalizationContext, prompt)
		recoveryReply = strings.TrimSpace(recoveryReply)
		if recoveryError == nil && recoveryReply != "" {
			return recoveryReply, nil
		}
		return recoveryReply, recoveryError
	}
	reply, errorValue := agentTurnRunner.recoveryLanguageModel.GenerateResponse(finalizationContext, prompt)
	return strings.TrimSpace(reply), errorValue
}

func (agentTurnRunner *AgentTurnRunner) generateLocalRecoveryText(prompt string) (string, error) {
	localRecoveryProvider, isLocalRecoveryProvider := agentTurnRunner.recoveryLanguageModel.(llm.LocalRecoveryResponder)
	if !isLocalRecoveryProvider {
		return "", errors.New("local recovery provider unavailable")
	}
	finalizationContext, cancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer cancel()
	reply, errorValue := localRecoveryProvider.GenerateLocalRecoveryResponse(finalizationContext, prompt)
	return strings.TrimSpace(reply), errorValue
}

func buildRecoveryDecisionPrompt(request AgentTurnRequest, failureReason string, observations []turnObservation, attachments []FileAttachment, executionState ExecutionState, phase string) string {
	sections := []string{
		"Phase: " + strings.TrimSpace(phase),
	}
	if reason := strings.TrimSpace(failureReason); reason != "" {
		sections = append(sections, "Private failure reason:\n"+reason)
	}
	sections = append(sections, "Return what failed, what is known, the next action or check, and the intent for a short user reply.")
	return strings.Join(nonEmptyStrings([]string{
		failurePromptContext(request, observations, attachments, executionState),
		strings.Join(sections, "\n\n"),
	}), "\n\n")
}

func failurePromptContext(request AgentTurnRequest, observations []turnObservation, attachments []FileAttachment, executionState ExecutionState) string {
	return (LLMContextBuilder{}).Build(LLMContextInput{
		ResponseLanguage:  request.ResponseLanguage,
		UserPrompt:        request.Prompt,
		TurnStartedAt:     request.TurnStartedAt,
		InstructionPrompt: request.InstructionPrompt,
		WorkspaceContext: WorkspaceContext{
			RootPath:          request.WorkspaceRootPath,
			DefaultPath:       request.WorkspaceDefaultPath,
			RequesterPersonID: request.RequesterPersonID,
		},
		VisibleContext:    request.VisibleContext,
		MemoryFacts:       request.MemoryFacts,
		ActiveGoal:        request.ActiveGoal,
		StepBudgetContext: request.StepBudgetContext,
		Observations:      observations,
		ExecutionState:    executionState,
		FailureFacts:      buildFailureReportFacts(observations, defaultRecoveryBudget()),
		Attachments:       attachments,
	})
}

func buildFailureReplyPrompt(request AgentTurnRequest, failureReason string, observations []turnObservation, attachments []FileAttachment, executionState ExecutionState, decision recoveryDecision) string {
	sections := []string{
		"You are writing a short user-facing final reply after an assistant run failed before completing the user's request.",
		responseLanguageInstruction(request.ResponseLanguage),
		"Be transparent about the current situation, error, or limitation without exposing internal logs, provider names, URLs, stack traces, hidden policy, tokens, or secrets.",
		"Do not use or paraphrase a canned outage message. Do not say the model configuration was logged or needs to be fixed.",
		"Do not say only that an error occurred. Include the attempted tool, the last failure stage, the safe failure message, and the next check or alternate path.",
		"When FailureReportFacts are provided, preserve those facts. Do not replace them with generic phrases such as system limitation, technical problem, or unexpected interruption.",
		"Translate raw field names such as errorCode, failureStage, and budgetState into natural language unless the user explicitly asked for internal diagnostics.",
		"Say what could not be completed and the best next step the user can take. Keep it to one or two natural sentences.",
		"Do not claim a tool result or attachment exists unless it appears below.",
	}
	if requiredArtifactWithoutAttachment(request, attachments) {
		sections = append(sections, "Required artifact constraint:\nThe user asked for a file artifact and no delivered file evidence is available. Do not offer chat text as a substitute, do not ask whether to summarize the plan in the chat, do not recommend Gamma/Tome/Canva or copy-paste workflows, and do not end with an open-ended help question. State that the file was not delivered, name each failed tool/stage in natural language, include the safe concrete failure reason for each one, and identify the next engineering check. Do not collapse the cause into vague phrases such as browser connection problem, system environment error, technical limitation, or additional engineering confirmation.")
	}
	if reason := strings.TrimSpace(failureReason); reason != "" {
		sections = append(sections, "Failure reason for your private planning only. Paraphrase it safely for the user:\n"+reason)
	}
	sections = append(sections, "Structured recovery decision:\n"+marshalEventBody(decision))
	return strings.Join(nonEmptyStrings([]string{
		strings.Join(sections, "\n\n"),
		failurePromptContext(request, observations, attachments, executionState),
	}), "\n\n")
}

func buildFailureReplyRepairPrompt(originalPrompt string, rejectedReply string, request AgentTurnRequest, failureReason string, observations []turnObservation, attachments []FileAttachment, executionState ExecutionState, repairCount int) string {
	sections := []string{
		originalPrompt,
		"Previous draft was rejected because it was too vague, offered an invalid substitute, exposed raw diagnostics, or missed concrete failure facts.",
		"Rewrite the final reply in natural user-facing language. Preserve the concrete safe failure facts from FailureReportFacts instead of summarizing them as a system or browser problem.",
	}
	if requiredArtifactWithoutAttachment(request, attachments) {
		sections = append(sections, "This was a required artifact request. Do not offer chat text as a substitute, do not ask an open-ended follow-up, do not recommend external slide or document tools, and do not expose raw identifiers such as errorCode or operation_failed. Say the artifact was not attached, name each failed tool or stage in natural language, include each safe failure reason, and identify the next engineering check.")
	}
	if failureFacts := buildFailureReportFacts(observations, defaultRecoveryBudget()); len(failureFacts.Attempts) > 0 {
		sections = append(sections, "FailureReportFacts that must be reflected accurately:\n"+marshalEventBody(failureFacts))
	}
	sections = append(sections, failurePromptContext(request, observations, attachments, executionState))
	if reason := strings.TrimSpace(failureReason); reason != "" {
		sections = append(sections, "Private failure reason:\n"+reason)
	}
	if repairCount > 1 {
		sections = append(sections, "Use one or two Korean sentences. Be specific about the failed operation and the safe reason, but do not include internal paths or raw field names.")
	}
	sections = append(sections, "Rejected draft:\n"+strings.TrimSpace(rejectedReply))
	return strings.Join(sections, "\n\n")
}

func latestStructuredFailureObservation(observations []turnObservation) (turnObservation, bool) {
	for index := len(observations) - 1; index >= 0; index-- {
		observation := observations[index]
		if !observation.Failed() {
			continue
		}
		if strings.TrimSpace(observation.FailureCode()) == "" && strings.TrimSpace(observation.FailureStage()) == "" {
			continue
		}
		return observation, true
	}
	return turnObservation{}, false
}

func recoverySituationFor(reason string, observations []turnObservation, attachments []FileAttachment, fallbackKind string) string {
	combinedText := strings.ToLower(strings.Join([]string{reason, buildFailureObservationSummary(observations)}, "\n"))
	if strings.Contains(combinedText, "blocked_by_captcha") || strings.Contains(combinedText, "bot-detection") || strings.Contains(combinedText, "captcha") {
		return "browser_blocked"
	}
	if strings.Contains(combinedText, "attachment") || strings.Contains(combinedText, "file.deliver") || strings.Contains(combinedText, "첨부") {
		return "attachment_unavailable"
	}
	if fallbackKind == "limit" || strings.Contains(combinedText, "max_") || strings.Contains(combinedText, "limit") {
		return "limit"
	}
	if strings.Contains(combinedText, "llm") || strings.Contains(combinedText, "language model") || strings.Contains(combinedText, "model") {
		return "model_unavailable"
	}
	if len(attachments) == 0 && strings.Contains(combinedText, "file") {
		return "attachment_unavailable"
	}
	return "general"
}

func failureReplyIsInvalid(reply string, attachments []FileAttachment) bool {
	if strings.Contains(reply, "I am having trouble reaching the language model") {
		return true
	}
	if strings.Contains(reply, "model configuration") {
		return true
	}
	if strings.Contains(reply, "configuration can be fixed") {
		return true
	}
	if strings.Contains(reply, "예상치 못한 중단") {
		return true
	}
	if strings.Contains(reply, "정보를 정리하여 답변") {
		return true
	}
	if strings.Contains(reply, "창을 새로고침") {
		return true
	}
	if ValidateUserNoticeDelivery(reply) != nil {
		return true
	}
	return false
}

func failureReplyIsInvalidForRequest(reply string, request AgentTurnRequest, failureReason string, observations []turnObservation, attachments []FileAttachment) bool {
	if failureReplyIsInvalid(reply, attachments) {
		return true
	}
	if requiredArtifactWithoutAttachment(request, attachments) && requiredArtifactFailureReplyIsInvalid(reply) {
		return true
	}
	if requiredArtifactWithoutAttachment(request, attachments) {
		return false
	}
	return structuredFailureDetailsAreMissing(reply, failureReason, observations, attachments)
}

func requiredArtifactWithoutAttachment(request AgentTurnRequest, attachments []FileAttachment) bool {
	return requestRequiresFileAttachment(request) && len(attachments) == 0
}

func requestRequiresFileAttachment(request AgentTurnRequest) bool {
	if request.OutcomeContract.ArtifactRequirement == ArtifactRequirementRequired {
		return true
	}
	if len(request.RequiredAttachmentSuffixes) > 0 {
		return true
	}
	if requiredEvidenceContains(request.RequiredEvidenceTools, FileDeliverToolName) {
		return true
	}
	return evidenceAnyOfContainsTool(request.OutcomeContract.RequiredEvidenceAnyOf, FileDeliverToolName)
}

func requiredArtifactFailureReplyIsInvalid(reply string) bool {
	normalizedReply := strings.ToLower(strings.TrimSpace(reply))
	if normalizedReply == "" {
		return true
	}
	for _, fragment := range requiredArtifactFailureForbiddenFragments() {
		if strings.Contains(normalizedReply, fragment) {
			return true
		}
	}
	return false
}

func requiredArtifactFailureForbiddenFragments() []string {
	return []string{
		"errorcode",
		"failurestage",
		"budgetstate",
		"operation_failed",
		"externally-managed-environment",
		"modulenotfounderror",
		"browser connection problem",
		"system environment error",
		"technical limitation",
		"additional engineering",
		"브라우저 연결 문제",
		"시스템 환경 오류",
		"시스템 환경의 오류",
		"시스템 환경상",
		"기술적인 제약",
		"기술적으로 불가능",
		"추가적인 엔지니어링",
		"엔지니어링 확인",
		"텍스트로",
		"텍스트 형태",
		"정리해 드릴까요",
		"정리해드릴까요",
		"다른 방식으로 도움",
		"도움이 필요",
		"말씀해 주세요",
		"말씀해주세요",
		"gamma",
		"tome",
		"canva",
		"복사하여",
		"복사해서",
		"붙여넣",
		"온라인 도구",
		"외부 도구",
		"대신 드",
		"대신 제공",
	}
}

func structuredFailureDetailsAreMissing(reply string, failureReason string, observations []turnObservation, attachments []FileAttachment) bool {
	situation := recoverySituationFor(failureReason, observations, attachments, "failure")
	if situation == "browser_blocked" || situation == "attachment_unavailable" || situation == "limit" || situation == "model_unavailable" {
		return false
	}
	failure, isFound := latestStructuredFailureObservation(observations)
	if !isFound {
		return false
	}
	return !containsFailureDetail(reply, failure.FailureStage()) || !containsFailureDetail(reply, failure.FailureCode())
}

func containsFailureDetail(reply string, value string) bool {
	trimmedValue := strings.TrimSpace(value)
	if trimmedValue == "" {
		return true
	}
	return strings.Contains(strings.ToLower(reply), strings.ToLower(trimmedValue))
}

func (agentTurnRunner *AgentTurnRunner) GenerateLimitReachedReply(request AgentTurnRequest, stopReason string, observations []turnObservation, attachments []FileAttachment) string {
	reply, _, _ := agentTurnRunner.generateLimitReachedReply(request, stopReason, observations, attachments, ExecutionState{})
	return reply
}

func buildLimitReachedPrompt(request AgentTurnRequest, stopReason string, observations []turnObservation, attachments []FileAttachment, executionState ExecutionState, decision recoveryDecision) string {
	sections := []string{
		"You are writing a short user-facing final reply after a Blueclaw run reached its scope limit.",
		responseLanguageInstruction(request.ResponseLanguage),
		"Do not mention internal runtime jargon, counters, percentages, elapsed time, or exact limits.",
		"Say what was completed, what remains, and the best partial answer available from completed work.",
		"When FailureReportFacts are provided, preserve those facts. Do not replace them with generic phrases such as system limitation, technical problem, or unexpected interruption.",
		"Translate raw field names such as errorCode, failureStage, and budgetState into natural language unless the user explicitly asked for internal diagnostics.",
		"Do not claim a tool result or attachment exists unless it appears below.",
	}
	if requiredArtifactWithoutAttachment(request, attachments) {
		sections = append(sections, "Required artifact constraint:\nThe user asked for a file artifact and no delivered file evidence is available. Do not offer chat text as a substitute, do not ask whether to summarize the plan in the chat, do not recommend Gamma/Tome/Canva or copy-paste workflows, and do not end with an open-ended help question. State that the file was not delivered, name each failed tool/stage in natural language, include the safe concrete failure reason for each one, and identify the next engineering check. Do not collapse the cause into vague phrases such as browser connection problem, system environment error, technical limitation, or additional engineering confirmation.")
	}
	if observationSummary := buildLimitObservationSummary(observations); observationSummary != "" {
		sections = append(sections, "Completed observations:\n"+observationSummary)
	}
	if requirementSummary := buildLimitRequirementSummary(request, observations); requirementSummary != "" {
		sections = append(sections, "Remaining completion requirements:\n"+requirementSummary)
	}
	if failureFacts := buildFailureReportFacts(observations, defaultRecoveryBudget()); len(failureFacts.Attempts) > 0 {
		sections = append(sections, "FailureReportFacts that must be reflected accurately:\n"+marshalEventBody(failureFacts))
	}
	if reason := strings.TrimSpace(stopReason); reason != "" {
		sections = append(sections, "Internal stop reason for your planning only: "+reason)
	}
	sections = append(sections, "Structured recovery decision:\n"+marshalEventBody(decision))
	return strings.Join(nonEmptyStrings([]string{
		strings.Join(sections, "\n\n"),
		failurePromptContext(request, observationsWithoutAttachments(observations), attachments, executionState),
	}), "\n\n")
}

func observationsWithoutAttachments(observations []turnObservation) []turnObservation {
	sanitizedObservations := make([]turnObservation, 0, len(observations))
	for _, observation := range observations {
		observation.Output = ToolOutput{}
		observation.ImageRefs = nil
		observation.Attachments = nil
		sanitizedObservations = append(sanitizedObservations, observation)
	}
	return sanitizedObservations
}

func buildLimitReachedRepairPrompt(originalPrompt string, rejectedReply string, request AgentTurnRequest, attachments []FileAttachment, repairCount int) string {
	sections := []string{
		originalPrompt,
		"Previous draft was rejected because it either exposed internal runtime details or claimed an attachment/tool result that is not available.",
		"Rewrite the final reply in natural user-facing language. Do not mention budgets, counters, exact limits, tool-call counts, iterations, seconds, or minutes. Do not use the exact canned sentence from any previous fallback.",
	}
	if requiredArtifactWithoutAttachment(request, attachments) {
		sections = append(sections, "This was a required artifact request. Do not offer chat text as a substitute, do not ask an open-ended follow-up, do not recommend external slide or document tools, and do not expose raw identifiers such as errorCode or operation_failed. Say the artifact was not attached, name the failing tool or stage in natural language, and identify the next engineering check.")
	}
	if len(attachments) == 0 {
		sections = append(sections, "No attachments are available. You may say the requested file or HTML was not completed or not attached. Do not say that a file, HTML, PPTX, PDF, deck, slide, or notes were attached, sent, delivered, completed, or created successfully.")
	}
	if repairCount > 1 {
		sections = append(sections, "Use one or two Korean sentences. Apologize briefly, say the run stopped before completion, and say the user can retry. Avoid all attachment-success wording.")
	}
	sections = append(sections, "Rejected draft:\n"+strings.TrimSpace(rejectedReply))
	return strings.Join(sections, "\n\n")
}

func limitReachedReplyIsInvalid(reply string, request AgentTurnRequest, attachments []FileAttachment) bool {
	if containsForbiddenLimitReplyFragment(reply) {
		return true
	}
	if requiredArtifactWithoutAttachment(request, attachments) && requiredArtifactFailureReplyIsInvalid(reply) {
		return true
	}
	if ValidateUserNoticeDelivery(reply) != nil {
		return true
	}
	return false
}

func buildLimitObservationSummary(observations []turnObservation) string {
	lines := []string{}
	for _, observation := range observations {
		if observation.Failed() {
			continue
		}
		summary := strings.TrimSpace(observation.Summary)
		if summary == "" {
			summary = summarizeObservationContent(observation)
		}
		if summary == "" {
			continue
		}
		label := strings.TrimSpace(observation.Tool)
		if label == "" {
			label = strings.TrimSpace(observation.Action)
		}
		lines = append(lines, "- "+label+": "+summary)
		if len(lines) >= 8 {
			break
		}
	}
	return strings.Join(lines, "\n")
}

func buildFailureObservationSummary(observations []turnObservation) string {
	lines := []string{}
	for _, observation := range observations {
		content := strings.TrimSpace(observation.ContentText())
		if observation.Failed() {
			content = firstNonEmptyString(summarizeStructuredFailure(observation), content)
		}
		if content == "" {
			content = strings.TrimSpace(observation.Summary)
		}
		if content == "" {
			continue
		}
		label := strings.TrimSpace(observation.Tool)
		if label == "" {
			label = strings.TrimSpace(observation.Action)
		}
		if observation.Failed() {
			label = label + " failed"
		}
		lines = append(lines, "- "+label+": "+truncateText(compactWhitespace(redactUnsafeText(content)), 360))
		if len(lines) >= 8 {
			break
		}
	}
	return strings.Join(lines, "\n")
}

func buildLimitAttachmentSummary(attachments []FileAttachment) string {
	lines := []string{}
	for _, attachment := range attachments {
		filename := strings.TrimSpace(attachment.Filename)
		if filename == "" {
			continue
		}
		lines = append(lines, "- "+filename)
	}
	return strings.Join(lines, "\n")
}

func buildLimitRequirementSummary(request AgentTurnRequest, observations []turnObservation) string {
	requirements := deriveToolUseRequirements(request)
	lines := []string{}
	for _, requirement := range requirements {
		if matchingCompletionObservations(requirement, observations) != nil {
			continue
		}
		lines = append(lines, "- "+requirementLabel(requirement))
	}
	if len(lines) == 0 {
		return ""
	}
	return strings.Join(lines, "\n")
}

func containsForbiddenLimitReplyFragment(reply string) bool {
	normalizedReply := strings.ToLower(reply)
	for _, fragment := range []string{"budget", "예산", "%", "percent", "percentage", "iteration", "tool call", "tool-call", "counter", "minute", "minutes", "second", "seconds", "분 ", "초 "} {
		if strings.Contains(normalizedReply, fragment) {
			return true
		}
	}
	return false
}

func errorString(errorValue error) string {
	if errorValue == nil {
		return ""
	}
	return errorValue.Error()
}
